name: Build

on:
  pull_request: {}
  push:
    branches:
      - '**'        # matches every branch

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v3.0.0

      - name: setup .net core
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '6.0'
          
      - name: build
        run: dotnet build
        working-directory: ./src/Northwind/
